### ISSUE TITLE
Panic on engine.Search and engine.SearchOne

### ISSUE THREAD

**Issue by haukened** [latolukasz/beeorm#1]
I've followed the documentation, and i can succesfully use the `Load` and `Flush` methods, however when using `Search` or `SearchOne` i get the following panic:

```
runtime error: invalid memory address or nil pointer dereference
goroutine 13 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1802 +0x13a
panic({0x9b2a00, 0xd301a0})
	/usr/local/go/src/runtime/panic.go:1047 +0x262
main.(*PersonEntity).github.com/latolukasz/beeorm.getORM(0x0)
	<autogenerated>:1 +0x30
github.com/latolukasz/beeorm.initIfNeeded(0xc000401b60, {0xa98a28, 0x0})
	/home/david/go/pkg/mod/github.com/latolukasz/beeorm@v1.3.7/load_by_id.go:87 +0x62
github.com/latolukasz/beeorm.searchRow(0xc00000e030, 0x1, 0xc00013c840, 0xc000436570, {0xa98a28, 0x0}, {0x0, 0x0, 0x0})
	/home/david/go/pkg/mod/github.com/latolukasz/beeorm@v1.3.7/search.go:129 +0xc5
github.com/latolukasz/beeorm.searchOne(0xc00000e030, 0x1, 0xc00013c840, 0xc000436570, {0xa98a28, 0x0}, {0x0, 0x0, 0x0})
	/home/david/go/pkg/mod/github.com/latolukasz/beeorm@v1.3.7/search.go:199 +0xf5
github.com/latolukasz/beeorm.(*Engine).SearchOne(0xc00013c840, 0xc000436570, {0xa98a28, 0x0}, {0x0, 0x0, 0x0})
	/home/david/go/pkg/mod/github.com/latolukasz/beeorm@v1.3.7/engine.go:250 +0x96
main.TestDB.func1({0x7f514d1321c0, 0xc0004201c0}, 0xc0000f2200)
	/home/david/dev/wfi_api/routes.go:53 +0xe5
net/http.HandlerFunc.ServeHTTP(0xc0000ac2b0, {0x7f514d1321c0, 0xc0004201c0}, 0xc0000f2200)
	/usr/local/go/src/net/http/server.go:2047 +0x43
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc0000a0240, {0x7f514d1321c0, 0xc0004201c0}, 0xc0000f2200)
	/home/david/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:442 +0x27e
net/http.HandlerFunc.ServeHTTP(0xc0000ac2c0, {0x7f514d1321c0, 0xc0004201c0}, 0xc0000f2200)
	/usr/local/go/src/net/http/server.go:2047 +0x43
github.com/go-chi/chi/v5/middleware.RequestLogger.func1.1({0xa920f0, 0xc0000cc0e0}, 0xc0000f2100)
	/home/david/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/middleware/logger.go:57 +0x26b
net/http.HandlerFunc.ServeHTTP(0xc0000a81b0, {0xa920f0, 0xc0000cc0e0}, 0xc0000f2100)
	/usr/local/go/src/net/http/server.go:2047 +0x43
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc0000a0240, {0xa920f0, 0xc0000cc0e0}, 0xc0000f2100)
	/home/david/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:88 +0x288
net/http.serverHandler.ServeHTTP({0xc0000cc000}, {0xa920f0, 0xc0000cc0e0}, 0xc0000f2000)
	/usr/local/go/src/net/http/server.go:2879 +0x47a
net/http.(*conn).serve(0xc0000b2000, {0xa93d78, 0xc000420000})
	/usr/local/go/src/net/http/server.go:1930 +0x18b8
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3034 +0xa38
```

Using this entity:
```
type PersonEntity struct {
	beeorm.ORM  `orm:"redisCache=default;table=people"`
	ID          uint
	Private     bool   `orm:"required"`
	FirstName   string `orm:"required;length=30"`
	MiddleName  string `orm:"length=30"`
	LastName    string `orm:"required;length=30"`
	DateofBirth *time.Time
	CreatedAt   time.Time  `orm:"required;time"`
	UpdatedAt   *time.Time `orm:"time"`
}

var testPerson = &PersonEntity{
	Private:     false,
	FirstName:   "David",
	MiddleName:  "Eloit",
	LastName:    "Haukeness",
	DateofBirth: nil,
	CreatedAt:   time.Now(),
}
```

and this function:
```
func TestDB(engine *beeorm.Engine) http.HandlerFunc {
	return func(rw http.ResponseWriter, r *http.Request) {
		var person *PersonEntity
		found := engine.SearchOne(beeorm.NewWhere("LastName = ?", "Haukeness"), person)
		if found {
			render.JSON(rw, r, HttpResponse(200, person))
		} else {
			render.JSON(rw, r, HttpResponse(404))
		}
	}
}
```

**Comment by fabform** [comment]
Handy alternative list of [alternative search engines](https://fabform.io/a/alternative-search-engines)

**Comment by latolukasz** [comment]
Hi,

I realized my documentation is wrong, you are right. I updated my documentation.
You should always pass initialized entity:

instead of:
```go
var person *PersonEntity
found := engine.SearchOne(beeorm.NewWhere("LastName = ?", "Haukeness"), person)
```

please use

```go
person := &PersonEntity{}
found := engine.SearchOne(beeorm.NewWhere("LastName = ?", "Haukeness"), person)
```

of course i can add code that will initialize entity using reflection but it will affect performance a bit (extra reflection operation). These methods are used very often so it's better developers user above code to keep top performance.

Sorry i replied so late. I had my github notifications disabled, not it's fixed.
